### ISSUE TITLE
Add styleguide

### ISSUE THREAD

**Issue by benmanu** [silverstripeltd/project-skeleton#10]
https://github.com/benmanu/silverstripe-simple-styleguide

**Comment by micmania1** [comment]
@benmanu I was looking at http://atomicdocs.io/ instead. Have you used it before?

**Comment by benmanu** [comment]
@micmania1 cool nah haven't come across that one, looks interesting. Key is it ticking the right boxes, with it having all of the SilverStripe tinymce base elements, form etc setup as is, then giving room to extend for custom blocks (my one doesn't quite tackle that easily).

Something like Pattern Lab (http://patternlab.io/) is a bit too stand-alone, and isn't easy for everyone to jump into and contribute without specific context... I like the idea of keeping it in the SilverStripe ecosystem. Have you tried integrating it with an SS theme? Any specific pain points you spotted?

They use storybook in the CMS, so could be another track to go down - https://storybook.js.org/.

**Comment by Firesphere** [comment]
Resolved in #18
